### ISSUE TITLE
Problems which arose during the initialization of telestion-extension-mavlink

### ISSUE THREAD

**Issue by cb0s** [wuespace/telestion-extension-template#8]
- [x] Dependabot tries to find registry of own package which in beginning obviously doesn't exist.
- [x] README.md is not particularly clear about how to use .github.credentials.template (copy file and rename to .github.credentials)
- [x] Wrong name for publishing new packages as shown in _[image_0]_
- [x] Gradle action for downloading telestion maven packages fails because the keys from the .github.credentials file are not loaded

_[image_0]_
![grafik](https://user-images.githubusercontent.com/16071970/116819411-478c5c80-ab70-11eb-81c0-c58d13d2aca1.png)

**Comment by jvpichowski** [comment]
> Dependabot tries to find registry of own package which in beginning obviously doesn't exist.
Uff.. example?

> Wrong name for publishing new packages as shown in [image_0]
Looks right to me. GroupId.ArtifactId

**Comment by jvpichowski** [comment]
For me everything looks right now. Feel free to reopen the issue and comment on it.
